package com.testforge.testforge_backend.testsuite.entity;
import jakarta.persistence.*; import java.time.*; import java.util.*; import org.hibernate.annotations.BatchSize;
@Entity @Table(name="suite_scenario_result") public class SuiteScenarioResult {
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY) private Long id; @ManyToOne(fetch=FetchType.LAZY,optional=false) @JoinColumn(name="suite_run_id") private SuiteRun suiteRun;
 @Column(name="source_scenario_id") private Long sourceScenarioId; @Column(name="scenario_business_id_snapshot",nullable=false) private String scenarioBusinessIdSnapshot; @Column(name="description_snapshot",length=2000) private String descriptionSnapshot;
 @Enumerated(EnumType.STRING) @Column(nullable=false) private SuiteResultStatus status=SuiteResultStatus.PENDING; @Column(name="started_at") private LocalDateTime startedAt; @Column(name="completed_at") private LocalDateTime completedAt; @Column(name="duration_ms") private Long durationMs;
 @OneToMany(mappedBy="scenarioResult",cascade=CascadeType.ALL) @OrderBy("id") @BatchSize(size=50) private List<SuiteTestCaseResult> testCaseResults=new ArrayList<>();
 public SuiteScenarioResult(){} public SuiteScenarioResult(Long id,String businessId,String description){sourceScenarioId=id;scenarioBusinessIdSnapshot=businessId;descriptionSnapshot=description;} void setSuiteRun(SuiteRun v){suiteRun=v;} public void addTestCase(SuiteTestCaseResult r){r.setScenarioResult(this);testCaseResults.add(r);} public Long getId(){return id;} public String getScenarioBusinessIdSnapshot(){return scenarioBusinessIdSnapshot;} public String getDescriptionSnapshot(){return descriptionSnapshot;} public SuiteResultStatus getStatus(){return status;} public LocalDateTime getStartedAt(){return startedAt;} public LocalDateTime getCompletedAt(){return completedAt;} public Long getDurationMs(){return durationMs;} public List<SuiteTestCaseResult> getTestCaseResults(){return testCaseResults;}
 public void summarize(){startedAt=testCaseResults.stream().map(SuiteTestCaseResult::getStartedAt).filter(Objects::nonNull).min(LocalDateTime::compareTo).orElse(null);completedAt=testCaseResults.stream().map(SuiteTestCaseResult::getCompletedAt).filter(Objects::nonNull).max(LocalDateTime::compareTo).orElse(null);durationMs=startedAt==null||completedAt==null?null:Duration.between(startedAt,completedAt).toMillis();status=testCaseResults.stream().anyMatch(r->r.getStatus()==SuiteResultStatus.FAILED)?SuiteResultStatus.FAILED:testCaseResults.stream().anyMatch(r->r.getStatus()==SuiteResultStatus.PASSED)?SuiteResultStatus.PASSED:SuiteResultStatus.SKIPPED;}
}
