package com.testforge.testforge_backend.testsuite.entity;
import jakarta.persistence.*; import java.time.*; import java.util.*; import org.hibernate.annotations.BatchSize;
@Entity @Table(name="suite_test_case_result") public class SuiteTestCaseResult {
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY) private Long id; @ManyToOne(fetch=FetchType.LAZY,optional=false) @JoinColumn(name="scenario_result_id") private SuiteScenarioResult scenarioResult;
 @Column(name="source_test_case_id") private Long sourceTestCaseId; @Column(name="test_case_business_id_snapshot",nullable=false) private String testCaseBusinessIdSnapshot; @Column(name="name_snapshot",nullable=false) private String nameSnapshot; @Column(name="automation_execution_id") private Long automationExecutionId;
 @Enumerated(EnumType.STRING) @Column(nullable=false) private SuiteResultStatus status=SuiteResultStatus.PENDING; @Column(name="started_at") private LocalDateTime startedAt; @Column(name="completed_at") private LocalDateTime completedAt; @Column(name="duration_ms") private Long durationMs; @Column(name="failure_details",columnDefinition="text") private String failureDetails; @Column(name="assertion_failure_details",columnDefinition="text") private String assertionFailureDetails; @Column(name="screenshot_path") private String screenshotPath; @Column(name="artifact_directory") private String artifactDirectory; @Column(name="trace_path") private String tracePath;
 @OneToMany(mappedBy="testCaseResult",cascade=CascadeType.ALL) @OrderBy("stepOrder") @BatchSize(size=50) private List<SuiteTestStepResult> stepResults=new ArrayList<>();
 public SuiteTestCaseResult(){} public SuiteTestCaseResult(Long id,String businessId,String name){sourceTestCaseId=id;testCaseBusinessIdSnapshot=businessId;nameSnapshot=name;} void setScenarioResult(SuiteScenarioResult v){scenarioResult=v;} public void addStep(SuiteTestStepResult r){r.setTestCaseResult(this);stepResults.add(r);} public Long getSourceTestCaseId(){return sourceTestCaseId;} public String getTestCaseBusinessIdSnapshot(){return testCaseBusinessIdSnapshot;} public String getNameSnapshot(){return nameSnapshot;} public SuiteResultStatus getStatus(){return status;} public LocalDateTime getStartedAt(){return startedAt;} public LocalDateTime getCompletedAt(){return completedAt;} public Long getDurationMs(){return durationMs;} public String getFailureDetails(){return failureDetails;} public String getAssertionFailureDetails(){return assertionFailureDetails;} public String getScreenshotPath(){return screenshotPath;} public String getArtifactDirectory(){return artifactDirectory;} public String getTracePath(){return tracePath;} public List<SuiteTestStepResult> getStepResults(){return stepResults;}
 public void finish(Long executionId,SuiteResultStatus s,LocalDateTime start,LocalDateTime end,Long duration,String error,Integer failedOrder,String screenshot,String artifact,String trace){automationExecutionId=executionId;status=s;startedAt=start;completedAt=end;durationMs=duration;failureDetails=error;assertionFailureDetails=failedOrder==null?null:"Automation step "+failedOrder+" failed";screenshotPath=screenshot;artifactDirectory=artifact;tracePath=trace;for(SuiteTestStepResult step:stepResults)step.finish(s,failedOrder,error,screenshot,artifact);}
 public void skip(String error){status=SuiteResultStatus.SKIPPED;failureDetails=error;for(SuiteTestStepResult step:stepResults)step.skip();}
}
