package com.testforge.testforge_backend.testsuite.service;
import com.testforge.testforge_backend.automation.dto.GeneratedScriptResponse; import com.testforge.testforge_backend.automation.entity.AutomationScript; import com.testforge.testforge_backend.automation.exception.AutomationNotFoundException; import com.testforge.testforge_backend.automation.service.AutomationGenerationService; import com.testforge.testforge_backend.domain.*; import com.testforge.testforge_backend.repository.*; import com.testforge.testforge_backend.testsuite.dto.SuiteJUnitConfiguration; import com.testforge.testforge_backend.testsuite.entity.*; import com.testforge.testforge_backend.testsuite.repository.TestSuiteRepository; import com.testforge.testforge_backend.testsuite.exception.InvalidTestSuiteException; import org.junit.jupiter.api.Test; import java.io.*; import java.time.LocalDateTime; import java.util.*; import java.util.zip.*; import static org.junit.jupiter.api.Assertions.*; import static org.mockito.Mockito.*;
class TestSuiteExportServiceTest {
 @Test void exportsSelectedScenarioAsPortableMavenProject()throws Exception{Fixture f=new Fixture();var exported=f.service.export("PRJ-1",5L);Map<String,String> entries=entries(exported.content());assertEquals("Nightly-Suite.zip",exported.fileName());assertTrue(entries.containsKey("pom.xml"));assertTrue(entries.containsKey("src/test/java/generated/testforge/LoginTest.java"));assertTrue(entries.get("pom.xml").contains("com.microsoft.playwright"));assertTrue(entries.get("pom.xml").contains("junit-jupiter"));assertTrue(entries.get("testforge-suite.properties").contains("scenario.ids=SC-1"));assertTrue(entries.get("src/test/resources/junit-platform.properties").contains("parallel.enabled=true"));assertTrue(entries.get("src/test/java/generated/testforge/LoginTest.java").contains("@org.junit.jupiter.api.Tag(\"smoke\")"));}
 @Test void missingAutomationNamesTestCase(){Fixture f=new Fixture();when(f.scripts.findByTestCaseId(7L)).thenReturn(Optional.empty());AutomationNotFoundException e=assertThrows(AutomationNotFoundException.class,()->f.service.export("PRJ-1",5L));assertEquals("Test Case \"Valid login\" (TC-7) has no automation script configured.",e.getMessage());}
 @Test void rejectsCrossProjectExport(){Fixture f=new Fixture();assertThrows(InvalidTestSuiteException.class,()->f.service.export("OTHER",5L));}
 private static Map<String,String> entries(byte[] value)throws Exception{Map<String,String> result=new HashMap<>();try(ZipInputStream zip=new ZipInputStream(new ByteArrayInputStream(value))){ZipEntry e;while((e=zip.getNextEntry())!=null)result.put(e.getName(),new String(zip.readAllBytes()));}return result;}
 private static class Fixture{final TestSuiteRepository suites=mock(TestSuiteRepository.class);final TestCaseRepository cases=mock(TestCaseRepository.class);final AutomationScriptRepository scripts=mock(AutomationScriptRepository.class);final AutomationGenerationService generation=mock(AutomationGenerationService.class);final TestSuiteService suiteService=mock(TestSuiteService.class);final TestSuiteExportService service=new TestSuiteExportService(suites,cases,scripts,generation,suiteService,new JUnitSuiteSourceTransformer());Fixture(){TestSuite suite=mock(TestSuite.class);Project project=mock(Project.class);TestSuiteScenario member=mock(TestSuiteScenario.class);TestScenario scenario=mock(TestScenario.class);TestCase testCase=mock(TestCase.class);AutomationScript script=mock(AutomationScript.class);when(suiteService.configuration(5L)).thenReturn(new SuiteJUnitConfiguration(SuiteExecutionMode.PARALLEL,true,List.of("smoke"),List.of(),List.of()));when(suites.findById(5L)).thenReturn(Optional.of(suite));when(suite.getProject()).thenReturn(project);when(project.getProjectId()).thenReturn("PRJ-1");when(suite.getId()).thenReturn(5L);when(suite.getName()).thenReturn("Nightly Suite");when(suite.getScenarios()).thenReturn(List.of(member));when(member.getScenario()).thenReturn(scenario);when(scenario.isAutomatable()).thenReturn(true);when(scenario.getScenarioId()).thenReturn("SC-1");when(cases.findByTestScenarioOrderByIdAsc(scenario)).thenReturn(List.of(testCase));when(testCase.getId()).thenReturn(7L);when(testCase.getName()).thenReturn("Valid login");when(testCase.getTestCaseId()).thenReturn("TC-7");when(scripts.findByTestCaseId(7L)).thenReturn(Optional.of(script));when(script.getId()).thenReturn(9L);when(generation.getGenerated(9L)).thenReturn(new GeneratedScriptResponse(9L,"AS-9",7L,"LoginTest","Java 17","Playwright","package generated.testforge;\npublic class LoginTest {}",1,LocalDateTime.now(),false));}}
}
