package com.testforge.testforge_backend.gitintegration.service;

import com.testforge.testforge_backend.domain.Project;
import com.testforge.testforge_backend.exception.ProjectNotFoundException;
import com.testforge.testforge_backend.repository.ProjectRepository;
import com.testforge.testforge_backend.testsuite.entity.TestSuite;
import com.testforge.testforge_backend.testsuite.repository.TestSuiteRepository;
import com.testforge.testforge_backend.testsuite.service.TestSuiteExportService;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.*;

@Service @Transactional(readOnly=true)
public class ProjectAutomationProjectGenerator {
    private final ProjectRepository projects; private final TestSuiteRepository suites; private final TestSuiteExportService exports;
    public ProjectAutomationProjectGenerator(ProjectRepository projects,TestSuiteRepository suites,TestSuiteExportService exports){this.projects=projects;this.suites=suites;this.exports=exports;}
    public GeneratedAutomationProject generate(String projectId){
        Project project=projects.findByProjectId(projectId).orElseThrow(()->new ProjectNotFoundException("Project not found: "+projectId));
        Map<String,String> files=new TreeMap<>(); List<String> modules=new ArrayList<>();
        for(TestSuite suite:suites.findByProjectOrderByIdAsc(project)){
            var generated=exports.generateFiles(projectId,suite.getId());
            String module="suites/"+TestSuiteExportService.fileName(suite.getName()).toLowerCase(Locale.ROOT)+"-"+suite.getId();
            modules.add(module);
            generated.files().forEach((path,content)->files.put(module+"/"+path,content));
        }
        files.put("pom.xml",rootPom(project,modules));
        files.put("README.md","# "+project.getName()+" TestForge automation\n\nGenerated by TestForge. Run all suites with `mvn clean test`, or select a module with `mvn -pl suites/<suite> test`.\n");
        return new GeneratedAutomationProject(Map.copyOf(files),hash(files));
    }
    private String rootPom(Project project,List<String> modules){
        String moduleXml=modules.stream().map(m->"<module>"+m+"</module>").reduce("",String::concat);
        String artifact=TestSuiteExportService.fileName(project.getName()).toLowerCase(Locale.ROOT)+"-automation";
        return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<project xmlns=\"http://maven.apache.org/POM/4.0.0\"><modelVersion>4.0.0</modelVersion><groupId>com.testforge.generated</groupId><artifactId>"+artifact+"</artifactId><version>1.0.0</version><packaging>pom</packaging><modules>"+moduleXml+"</modules></project>\n";
    }
    static String hash(Map<String,String> files){try{MessageDigest d=MessageDigest.getInstance("SHA-256");files.entrySet().stream().sorted(Map.Entry.comparingByKey()).forEach(e->{d.update(e.getKey().getBytes(StandardCharsets.UTF_8));d.update((byte)0);d.update(e.getValue().getBytes(StandardCharsets.UTF_8));d.update((byte)0);});return HexFormat.of().formatHex(d.digest());}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
}
