package com.testforge.testforge_backend.gitintegration.service;
import com.testforge.testforge_backend.domain.Project; import com.testforge.testforge_backend.repository.ProjectRepository; import com.testforge.testforge_backend.testsuite.entity.TestSuite; import com.testforge.testforge_backend.testsuite.repository.TestSuiteRepository; import com.testforge.testforge_backend.testsuite.service.TestSuiteExportService; import org.junit.jupiter.api.Test;
import java.util.*; import static org.junit.jupiter.api.Assertions.*; import static org.mockito.Mockito.*;
class ProjectAutomationProjectGeneratorTest {
 @Test void composesMultipleUiAndApiSuitesFromSharedExportGenerator(){
  Project project=new Project();project.setProjectId("PRJ-1");project.setName("Customer Portal");ProjectRepository projects=mock(ProjectRepository.class);when(projects.findByProjectId("PRJ-1")).thenReturn(Optional.of(project));TestSuite smoke=mock(TestSuite.class),api=mock(TestSuite.class);when(smoke.getId()).thenReturn(1L);when(smoke.getName()).thenReturn("Smoke");when(api.getId()).thenReturn(2L);when(api.getName()).thenReturn("API Regression");TestSuiteRepository suites=mock(TestSuiteRepository.class);when(suites.findByProjectOrderByIdAsc(project)).thenReturn(List.of(smoke,api));TestSuiteExportService exports=mock(TestSuiteExportService.class);when(exports.generateFiles("PRJ-1",1L)).thenReturn(new TestSuiteExportService.GeneratedSuiteProject(1L,"Smoke",Map.of("pom.xml","ui-pom","src/test/java/generated/testforge/LoginTest.java","class LoginTest {}")));when(exports.generateFiles("PRJ-1",2L)).thenReturn(new TestSuiteExportService.GeneratedSuiteProject(2L,"API Regression",Map.of("pom.xml","api-pom","src/test/java/generated/testforge/DashboardApiTest.java","class DashboardApiTest {}")));
  GeneratedAutomationProject generated=new ProjectAutomationProjectGenerator(projects,suites,exports).generate("PRJ-1");assertTrue(generated.files().containsKey("suites/smoke-1/src/test/java/generated/testforge/LoginTest.java"));assertTrue(generated.files().containsKey("suites/api-regression-2/src/test/java/generated/testforge/DashboardApiTest.java"));assertTrue(generated.files().get("pom.xml").contains("<module>suites/smoke-1</module>"));assertTrue(generated.files().get("pom.xml").contains("<module>suites/api-regression-2</module>"));assertEquals(generated.contentHash(),new ProjectAutomationProjectGenerator(projects,suites,exports).generate("PRJ-1").contentHash());
 }
}
