package com.testforge.testforge_backend.testsuite.service;
import com.fasterxml.jackson.core.type.TypeReference; import com.fasterxml.jackson.databind.ObjectMapper; import com.testforge.testforge_backend.domain.*; import com.testforge.testforge_backend.exception.ProjectNotFoundException; import com.testforge.testforge_backend.repository.*; import com.testforge.testforge_backend.testsuite.dto.*; import com.testforge.testforge_backend.testsuite.entity.*; import com.testforge.testforge_backend.testsuite.repository.*; import com.testforge.testforge_backend.testsuite.exception.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDateTime; import java.util.*;
@Service @Transactional public class TestSuiteService {private final TestSuiteRepository suites;private final ProjectRepository projects;private final TestScenarioRepository scenarios;private final ObjectMapper json=new ObjectMapper();private final SuiteRunRepository suiteRuns;public TestSuiteService(TestSuiteRepository a,ProjectRepository b,TestScenarioRepository c,SuiteRunRepository d){suites=a;projects=b;scenarios=c;suiteRuns=d;}
 public TestSuiteResponse create(String projectId,TestSuiteRequest r){Project p=project(projectId);if(suites.existsByProjectAndNameIgnoreCase(p,r.name().trim()))throw new InvalidTestSuiteException("Test Suite name already exists in Project");TestSuite s=new TestSuite();s.setProject(p);s.setName(r.name().trim());s.setDescription(norm(r.description()));applySettings(s,r);LocalDateTime n=LocalDateTime.now();s.setCreatedAt(n);s.setUpdatedAt(n);s.replaceScenarios(items(p,r.scenarioIds()));return response(suites.save(s));}
 public TestSuiteResponse update(Long id,TestSuiteRequest r){TestSuite s=find(id);if(suites.existsByProjectAndNameIgnoreCaseAndIdNot(s.getProject(),r.name().trim(),id))throw new InvalidTestSuiteException("Test Suite name already exists in Project");s.setName(r.name().trim());s.setDescription(norm(r.description()));applySettings(s,r);s.replaceScenarios(items(s.getProject(),r.scenarioIds()));s.setUpdatedAt(LocalDateTime.now());return response(s);}
 @Transactional(readOnly=true)public List<TestSuiteResponse> byProject(String id){Project p=project(id);return suites.findByProjectOrderByIdAsc(p).stream().map(this::response).toList();}public void delete(Long id){TestSuite suite=find(id);if(suiteRuns.countByTestSuiteIdSnapshotAndStatusIn(id,List.of(SuiteResultStatus.PENDING,SuiteResultStatus.RUNNING))>0)throw new InvalidTestSuiteException("A Suite Run is currently active. Wait for it to finish before deleting this Test Suite.");suite.replaceScenarios(List.of());suites.flush();suites.delete(suite);}
 @Transactional(readOnly=true)public List<TestSuiteResponse.ScenarioMember> candidates(String id){Project p=project(id);int[] order={1};return scenarios.findAutomatableByProjectId(p.getId()).stream().map(s->new TestSuiteResponse.ScenarioMember(s.getId(),s.getScenarioId(),s.getDescription(),order[0]++)).toList();}
 @Transactional(readOnly=true)public SuiteJUnitConfiguration configuration(Long id){return config(find(id));}
 private void applySettings(TestSuite s,TestSuiteRequest r){List<String> extensions=r.extensions()==null?List.of():r.extensions();if(!extensions.isEmpty())throw new InvalidTestSuiteException("No JUnit extensions are currently supported by TestForge.");List<Map<String,String>> parameters=r.parameterSets()==null?List.of():r.parameterSets();for(Map<String,String> set:parameters){if(set==null||set.isEmpty())throw new InvalidTestSuiteException("Each parameter set must contain at least one value.");if(set.values().stream().anyMatch(Objects::isNull))throw new InvalidTestSuiteException("Parameter values must not be null.");}s.setExecutionMode(r.executionMode()==null?SuiteExecutionMode.SEQUENTIAL:r.executionMode());s.setLifecycleEnabled(r.lifecycleEnabled()==null||r.lifecycleEnabled());s.setJunitTags(String.join(",",r.tags()==null?List.of():new LinkedHashSet<>(r.tags())));s.setJunitExtensions("");try{s.setParameterSetsJson(parameters.isEmpty()?null:json.writeValueAsString(parameters));}catch(Exception e){throw new InvalidTestSuiteException("JUnit parameter sets are invalid.");}}
 private SuiteJUnitConfiguration config(TestSuite s){return new SuiteJUnitConfiguration(s.getExecutionMode(),s.isLifecycleEnabled(),split(s.getJunitTags()),parameters(s.getParameterSetsJson()),split(s.getJunitExtensions()));}
 private List<Map<String,String>> parameters(String value){if(value==null||value.isBlank())return List.of();try{return json.readValue(value,new TypeReference<>(){});}catch(Exception e){throw new InvalidTestSuiteException("Stored JUnit parameter configuration is invalid.");}}
 private List<String> split(String value){return value==null||value.isBlank()?List.of():Arrays.stream(value.split(",")).filter(v->!v.isBlank()).toList();}
 private List<TestSuiteScenario> items(Project p,List<Long> ids){List<TestSuiteScenario> out=new ArrayList<>();int order=1;for(Long id:new LinkedHashSet<>(ids)){TestScenario s=scenarios.findById(id).orElseThrow(()->new InvalidTestSuiteException("Scenario not found: "+id));Project actual=s.getRequirement().getModule().getProject();if(!actual.getId().equals(p.getId()))throw new InvalidTestSuiteException("Scenario belongs to another Project");if(!s.isAutomatable())throw new InvalidTestSuiteException("Scenario is not automatable: "+s.getScenarioId());out.add(new TestSuiteScenario(s,order++));}return out;}
 private Project project(String id){return projects.findByProjectId(id).orElseThrow(()->new ProjectNotFoundException("Project not found: "+id));}private TestSuite find(Long id){return suites.findById(id).orElseThrow(()->new TestSuiteNotFoundException("Test Suite not found: "+id));}private String norm(String v){return v==null||v.isBlank()?null:v.trim();}private TestSuiteResponse response(TestSuite s){SuiteJUnitConfiguration c=config(s);return new TestSuiteResponse(s.getId(),s.getProject().getId(),s.getProject().getProjectId(),s.getName(),s.getDescription(),s.getScenarios().stream().map(i->new TestSuiteResponse.ScenarioMember(i.getScenario().getId(),i.getScenario().getScenarioId(),i.getScenario().getDescription(),i.getItemOrder())).toList(),c.executionMode(),c.lifecycleEnabled(),c.tags(),c.parameterSets(),c.extensions(),s.getCreatedAt(),s.getUpdatedAt());}}
