import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { gitIntegrationApi } from '../../api/gitIntegrationApi';
import GitIntegrationPage from './GitIntegrationPage';

vi.mock('../../api/gitIntegrationApi',()=>({gitIntegrationApi:{get:vi.fn(),save:vi.fn(),testConnection:vi.fn(),changes:vi.fn(),sync:vi.fn()}}));
const project={id:1,projectId:'PRJ-1',name:'Portal',status:'ACTIVE' as const,createdAt:'2026-01-01',updatedAt:'2026-01-01'};
const configured={configured:true,projectId:'PRJ-1',repositoryUrl:'https://example.com/tests.git',branch:'main',automationProjectPath:'testforge-automation',commitMessageTemplate:'TestForge: Update Portal automation',credentialConfigured:true,status:'CHANGES_PENDING' as const,lastSyncAt:null,lastCommitSha:null,lastErrorSummary:null,recentSyncs:[]};
describe('GitIntegrationPage',()=>{
 beforeEach(()=>{vi.clearAllMocks();vi.mocked(gitIntegrationApi.get).mockResolvedValue(configured);vi.mocked(gitIntegrationApi.changes).mockResolvedValue({added:['suites/smoke/pom.xml'],modified:[],deleted:[],hasChanges:true});vi.mocked(gitIntegrationApi.sync).mockResolvedValue({status:'SYNCED',message:'Automation committed and pushed.',commitSha:'abc123',changes:{added:['suites/smoke/pom.xml'],modified:[],deleted:[],hasChanges:true}});});
 it('shows configuration, ownership, and manual sync status',async()=>{render(<GitIntegrationPage project={project}/>);expect(await screen.findByDisplayValue('https://example.com/tests.git')).toBeInTheDocument();expect(screen.getByText(/owns only this repository directory/i)).toBeInTheDocument();expect(screen.getByText('CHANGES PENDING')).toBeInTheDocument();expect(screen.getByText(/never commits or pushes automatically/i)).toBeInTheDocument();});
 it('requires review confirmation before commit and push',async()=>{const user=userEvent.setup();render(<GitIntegrationPage project={project}/>);await screen.findByDisplayValue('https://example.com/tests.git');await user.click(screen.getByRole('button',{name:'Sync to Git'}));expect(await screen.findByRole('heading',{name:'Sync Automation to Git'})).toBeInTheDocument();expect(gitIntegrationApi.sync).not.toHaveBeenCalled();expect(screen.getByText('+ suites/smoke/pom.xml')).toBeInTheDocument();await user.click(screen.getByRole('button',{name:'Commit & Push'}));await waitFor(()=>expect(gitIntegrationApi.sync).toHaveBeenCalledWith('PRJ-1','TestForge: Update Portal automation'));});
 it('submits a credential but never receives or renders its value',async()=>{const user=userEvent.setup();vi.mocked(gitIntegrationApi.save).mockResolvedValue(configured);render(<GitIntegrationPage project={project}/>);await screen.findByDisplayValue('https://example.com/tests.git');await user.type(screen.getByLabelText('Access Token'),'secret-token');await user.click(screen.getByRole('button',{name:'Save Configuration'}));await waitFor(()=>expect(gitIntegrationApi.save).toHaveBeenCalledWith('PRJ-1',expect.objectContaining({credentialToken:'secret-token'})));expect(screen.queryByDisplayValue('secret-token')).not.toBeInTheDocument();});
});
